### ISSUE TITLE
User erstellen ohne Daten und Dopllelte Anmeldung

### ISSUE THREAD

**Issue by mjay1304** [Skillkiller/Login#1]
Du kannst User erstellen ohne irgendwas einzugeben. 

Einmal fixen, u know.

**Comment by Skillkiller** [comment]
Ja wird in der nächsten Version gefixt
:+1:

**Comment by Skillkiller** [comment]
Bug besteht noch immer... User können dich auch 2 mal mit dem selben Namen regestieren

**Comment by Skillkiller** [comment]
Das Problem ist nun endgültig gefixt
