### ISSUE TITLE
Zugriff auf Administration

### ISSUE THREAD

**Issue by Skillkiller** [Skillkiller/Login#3]
Egal ob der User Administrator ist oder nicht er kann auf die ACP Oberfläche zugreifen

**Comment by mjay1304** [comment]
> Der Zugriffspunkt auf das ACP hat bisher noch keine Funktion zugewiesen bekommen. In der Version 1.1.1 werd Ich sämtliche Bugfixes lösen und unter Administration werden einige Funktionen der Administration aktiviert.

Siehe: https://gist.github.com/xHAGAKURE/c9fd2c1080a724ae6b7ea73e28844b75
- HAGAKURE (15:30)
