### ISSUE TITLE
Handy Version

### ISSUE THREAD

**Issue by Skillkiller** [Skillkiller/Login#4]
In der Handy Version geht das Menü nicht

**Comment by mjay1304** [comment]
Welches Menü?

**Comment by Skillkiller** [comment]
#Interne Klärung

**Comment by mjay1304** [comment]
Das CP wird heute ein neues Design erhalten. Das Problem sollte damit gelöst werden.

**Comment by mjay1304** [comment]
Änderung: Im Laufe des morgigen Tages (28.08.2016) werden ich das Update einspielen lassen
